require 'uri'
require 'json'
require 'scissors'
require 'scissors/encryption'

# Verifies signed tokens generated by an authentication server
class Scissors::Client
  include Scissors::Encryption
  attr_reader :app, :key, :uri

  def initialize(app, key, uri)
    @app = app.freeze
    @key = key.freeze
    @uri = URI.parse(uri).freeze
  end

  def authentication_url(request_id)
    request_id = CGI.escape request_id
    app = CGI.escape @app
    signature = CGI.escape sign(request_id)
    @uri + "?app=#{app}&request=#{request_id}&signature=#{signature}"
  end

  def extract_url_param(plaintext, signature)
    plaintext if valid?(plaintext, signature)
  end

end
